# Generated by Django 4.1.1 on 2022-09-12 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_add_band_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='title',
        ),
    ]
