# Generated by Django 4.1.1 on 2022-09-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_band_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Add',
            new_name='Ad',
        ),
    ]
