# Generated by Django 4.1.1 on 2022-09-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('sold', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('records', 'Records'), ('clothings', 'Clothing'), ('miscellaneous', 'Miscellaneous')], max_length=30)),
            ],
        ),
    ]
