# Generated by Django 4.1.1 on 2022-09-15 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_productos_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('sold', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('records', 'Records'), ('clothings', 'Clothing'), ('miscellaneous', 'Miscellaneous')], max_length=30)),
                ('band', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band')),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
