# Generated by Django 4.1.1 on 2022-09-15 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_products_delete_productos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
